INSERT INTO QUIZ (name, owner_id, creation_date) VALUES ('JEUX OLYMPIQUES', 1, '2021-03-15');
INSERT INTO PARTICIPANT (name, email, quiz_id, token, invitation_date, relance_date, participation_date, timer, completion_rate, success_rate) VALUES (null, 'flavien.licata@hotmail.fr', 1, 'token', '2021-03-16', null, '2021-03-17', 500, 50, 50);
INSERT INTO PARTICIPANT (name, email, quiz_id, token, invitation_date, relance_date, participation_date, timer, completion_rate, success_rate) VALUES (null, 'flavien.licata@hotmail.fr', 1, 'token2', '2021-03-16', null, null, null, 82.3, 74.2);
INSERT INTO QUESTION (quiz_id, title) VALUES (1, 'En quelle année se sont déroulés les Jeux Olympiques d’hiver d’Albertville ?');
INSERT INTO QUESTION (quiz_id, title) VALUES (1, 'Que représentent les 5 anneaux olympiques ?');
INSERT INTO ANSWER (quiz_id, question_id, title, correct) VALUES (1, 1, '1982', false);
INSERT INTO ANSWER (quiz_id, question_id, title, correct) VALUES (1, 1, '1968', false);
INSERT INTO ANSWER (quiz_id, question_id, title, correct) VALUES (1, 1, '1992', true);
INSERT INTO ANSWER (quiz_id, question_id, title, correct) VALUES (1, 1, '2002', false);
INSERT INTO ANSWER (quiz_id, question_id, title, correct) VALUES (1, 2, 'Les 5 continents', true);
INSERT INTO ANSWER (quiz_id, question_id, title, correct) VALUES (1, 2, 'Les 5 doigts de la main', false);
INSERT INTO ANSWER (quiz_id, question_id, title, correct) VALUES (1, 2, 'Les 5 premiers sports olympiques', false);
INSERT INTO ANSWER (quiz_id, question_id, title, correct) VALUES (1, 2, 'Les 5 fondateurs des Jeux Olympiques', false);
INSERT INTO PARTICIPANT_ANSWER (quiz_id, participant_id, question_id, answer_id, correct) VALUES (1, 1, 1, null, false);
INSERT INTO PARTICIPANT_ANSWER (quiz_id, participant_id, question_id, answer_id, correct) VALUES (1, 1, 2, 5, true);